create table "QWER".HERO
(
	HERO_ID INTEGER not null primary key,
	HERO_LV INTEGER,
	HERO_HP INTEGER,
	HERO_ARMOR INTEGER,
	HERO_EXP INTEGER,
	HERO_ATK INTEGER,
	HERO_STATUS INTEGER,
	HERO_ITEM INTEGER,
	HERO_X INTEGER,
	HERO_Y INTEGER,
	HERO_X2 INTEGER,
	HERO_Y2 INTEGER,
	ITEM_1 BOOLEAN default true not null,
	ITEM_2 BOOLEAN default true not null,
	ITEM_3 BOOLEAN default true not null,
	ITEM_4 BOOLEAN default true not null,
	ITEM_5 BOOLEAN default true not null,
	MINIBOSS BOOLEAN default true not null,
	BOSS BOOLEAN default true not null
)

INSERT INTO QWER.HERO (HERO_ID, HERO_LV, HERO_HP, HERO_ARMOR, HERO_EXP, HERO_ATK, HERO_STATUS, HERO_ITEM, HERO_X, HERO_Y, HERO_X2, HERO_Y2, ITEM_1, ITEM_2, ITEM_3, ITEM_4, ITEM_5, MINIBOSS, BOSS) 
	VALUES (1, 10, 150, 50, 0, 40001, 1, 4, 5, 1, 330, 280, true, true, true, true, false, false, true);
INSERT INTO QWER.HERO (HERO_ID, HERO_LV, HERO_HP, HERO_ARMOR, HERO_EXP, HERO_ATK, HERO_STATUS, HERO_ITEM, HERO_X, HERO_Y, HERO_X2, HERO_Y2, ITEM_1, ITEM_2, ITEM_3, ITEM_4, ITEM_5, MINIBOSS, BOSS) 
	VALUES (2, 10, 940, 50, 0, 40001, 1, 6, 0, 0, 230, 240, false, false, false, false, false, false, true);
INSERT INTO QWER.HERO (HERO_ID, HERO_LV, HERO_HP, HERO_ARMOR, HERO_EXP, HERO_ATK, HERO_STATUS, HERO_ITEM, HERO_X, HERO_Y, HERO_X2, HERO_Y2, ITEM_1, ITEM_2, ITEM_3, ITEM_4, ITEM_5, MINIBOSS, BOSS) 
	VALUES (3, 4, 270, 20, 90, 60, 0, 4, 2, 1, 150, 120, false, false, false, false, true, true, true);


create table "QWER".MONSTER
(
	MON_ID INTEGER not null primary key,
	MON_HP INTEGER,
	MON_ATK INTEGER,
	MON_EXP INTEGER,
	MON_LV INTEGER
)

INSERT INTO QWER.MONSTER (MON_ID, MON_HP, MON_ATK, MON_EXP, MON_LV) 
	VALUES (1, 50, 10, 10, 1);
INSERT INTO QWER.MONSTER (MON_ID, MON_HP, MON_ATK, MON_EXP, MON_LV) 
	VALUES (2, 100, 20, 20, 2);
INSERT INTO QWER.MONSTER (MON_ID, MON_HP, MON_ATK, MON_EXP, MON_LV) 
	VALUES (3, 150, 30, 30, 3);
INSERT INTO QWER.MONSTER (MON_ID, MON_HP, MON_ATK, MON_EXP, MON_LV) 
	VALUES (4, 200, 40, 40, 4);
INSERT INTO QWER.MONSTER (MON_ID, MON_HP, MON_ATK, MON_EXP, MON_LV) 
	VALUES (5, 250, 50, 50, 5);
INSERT INTO QWER.MONSTER (MON_ID, MON_HP, MON_ATK, MON_EXP, MON_LV) 
	VALUES (6, 300, 60, 60, 6);
INSERT INTO QWER.MONSTER (MON_ID, MON_HP, MON_ATK, MON_EXP, MON_LV) 
	VALUES (7, 350, 70, 70, 7);
INSERT INTO QWER.MONSTER (MON_ID, MON_HP, MON_ATK, MON_EXP, MON_LV) 
	VALUES (8, 400, 80, 80, 8);
INSERT INTO QWER.MONSTER (MON_ID, MON_HP, MON_ATK, MON_EXP, MON_LV) 
	VALUES (9, 450, 90, 90, 9);
INSERT INTO QWER.MONSTER (MON_ID, MON_HP, MON_ATK, MON_EXP, MON_LV) 
	VALUES (10, 500, 100, 100, 10);
INSERT INTO QWER.MONSTER (MON_ID, MON_HP, MON_ATK, MON_EXP, MON_LV) 
	VALUES (11, 1000, 150, 100, 20);
INSERT INTO QWER.MONSTER (MON_ID, MON_HP, MON_ATK, MON_EXP, MON_LV) 
	VALUES (12, 40000, 2000, 0, 99);