/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author KMT
 */
public class GuiBattle extends javax.swing.JFrame {

    /**
     * Creates new form GuiBattle
     */
    public static int hero[] = new int[9];
    public static int mon[][] = new int[12][4];
    int ai = mon[GuiGame.ran][0];
    private javax.swing.JLabel jLabel1;

    public GuiBattle() {
        initComponents();
        jTextField1.setText(mon[GuiGame.ran][0] + "");

        jTextField5.setText(hero[0] + "");
        jTextField6.setText(hero[1] + "");
        jTextField7.setText(hero[4] + "");
        jTextField8.setText(hero[3] + "");
        jTextField9.setText(hero[2] + "");
        jTextField10.setText(hero[6] + "");

        jLabel1 = new javax.swing.JLabel();
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageJava2DGame/mon" + GuiGame.ran + ".png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 70, 128, 128);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageJava2DGame/cc.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(90, 190, 128, 128);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageJava2DGame/asas.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(230, 110, 260, 120);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageJava2DGame/asas.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 220, 260, 120);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageJava2DGame/battle.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 52, 500, 300);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setText("HP");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 11, 27, 20);

        jTextField1.setEnabled(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(41, 2, 60, 30);

        jLabel4.setText("ATK");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(118, 11, 33, 20);

        jTextField2.setEnabled(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(155, 2, 60, 30);

        jLabel5.setText("EXP");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(232, 11, 32, 20);

        jTextField3.setEnabled(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(268, 2, 60, 30);

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(415, 11, 75, 23);

        jLabel6.setText("LV");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 414, 34, 20);

        jTextField5.setEnabled(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(60, 410, 60, 30);

        jLabel7.setText("HP");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 414, 40, 20);

        jTextField6.setEnabled(false);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(200, 410, 60, 30);

        jLabel8.setText("ATK");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 414, 30, 20);

        jLabel11.setText("HpPotion");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(130, 460, 70, 30);

        jTextField7.setEnabled(false);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(300, 410, 60, 30);

        jLabel9.setText("EXP");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(370, 414, 30, 20);

        jTextField8.setEnabled(false);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(400, 410, 60, 30);

        jLabel10.setText("ARMOR");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 460, 50, 30);

        jTextField9.setEnabled(false);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(60, 460, 60, 30);

        jTextField10.setEnabled(false);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(200, 460, 60, 30);

        jButton3.setText("UseHpPotion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(180, 370, 120, 23);

        jButton2.setText("Attack");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 368, 110, 23);

        jButton4.setText("Scan");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(350, 368, 110, 23);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageJava2DGame/cc.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(90, 190, 128, 128);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageJava2DGame/asas.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(230, 110, 260, 120);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageJava2DGame/asas.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 220, 260, 120);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageJava2DGame/battle.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 52, 500, 300);

        jButton5.setText("Escape");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(353, 460, 110, 23);

        setSize(new java.awt.Dimension(516, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        Play p = new Play();
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText(mon[GuiGame.ran][1] + "");
        jTextField3.setText(mon[GuiGame.ran][2] + "");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Play p = new Play();
        int x = (int) (Math.random() * 3);
        if (x == 2) {
            ai = ai - (hero[4] * 2);
            JOptionPane.showMessageDialog(this, "Your Damage(Critical Damage):" + hero[4] * 2);
        } else {
            ai = ai - hero[4];
            JOptionPane.showMessageDialog(this, "Your Damage:" + hero[4]);
        }
        if (ai <= 0) {
            JOptionPane.showMessageDialog(this, "You Win");
            p.setExp(hero, mon, GuiGame.ran);
            GuiGame gui = new GuiGame();
            gui.setVisible(true);
            this.setVisible(false);
            if (ai <= 0 && GuiGame.ran == 10) {
                hero[5]=1;
            }else if (ai <= 0 && GuiGame.ran == 11) {
                JOptionPane.showMessageDialog(this, "Victory");
                System.exit(0);
            }
        } else if (hero[2] > mon[GuiGame.ran][1]) {
            hero[1] = hero[1];
        } else {
            hero[1] = hero[1] - (mon[GuiGame.ran][1] - hero[2]);
            if(hero[1]<0){
                hero[1]=0;
            }
            JOptionPane.showMessageDialog(this, "Receive Damage: " + (mon[GuiGame.ran][1] - hero[2]));
        }

        jTextField1.setText(ai + "");

        jTextField6.setText(hero[1] + "");

        if (hero[1] <= 0) {
            JOptionPane.showMessageDialog(this, "You lose");
            GuiStart gui = new GuiStart();
            gui.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (GuiBattle.hero[6] > 0) {
            switch (GuiBattle.hero[0]) {
                case 1:
                    GuiBattle.hero[1] = 100;
                    break;
                case 2:
                    GuiBattle.hero[1] = 200;
                    break;
                case 3:
                    GuiBattle.hero[1] = 300;
                    break;
                case 4:
                    GuiBattle.hero[1] = 400;
                    break;
                case 5:
                    GuiBattle.hero[1] = 500;
                    break;
                case 6:
                    GuiBattle.hero[1] = 600;
                    break;
                case 7:
                    GuiBattle.hero[1] = 700;
                    break;
                case 8:
                    GuiBattle.hero[1] = 800;
                    break;
                case 9:
                    GuiBattle.hero[1] = 900;
                    break;
                case 10:
                    GuiBattle.hero[1] = 1000;
                    break;
            }
            GuiBattle.hero[6]--;
        } else {
            JOptionPane.showMessageDialog(this, "Out of Stock.");
        }
        jTextField6.setText(GuiBattle.hero[1] + "");
        jTextField10.setText(GuiBattle.hero[6] + "");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(GuiGame.ran<10){
        GuiGame gui = new GuiGame();
        gui.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiBattle.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiBattle.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiBattle.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiBattle.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiBattle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
