/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author KMT
 */
public class GuiSaveGame extends javax.swing.JFrame {

    /**
     * Creates new form GuiSaveGame
     */
    public GuiSaveGame() {
        initComponents();
        Play p = new Play();
        try {
            Connection con = p.getConnection();
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("select * from hero where hero_id = 1");
            while (rs.next()) {
                jTextField1.setText(rs.getInt("hero_lv")+"");
                jTextField2.setText(rs.getInt("hero_hp")+"");
                jTextField3.setText(rs.getInt("hero_atk")+"");
                jTextField5.setText(rs.getInt("hero_armor")+"");
                jTextField6.setText(rs.getInt("hero_item")+"");
                jTextField4.setText(rs.getInt("hero_exp")+"");
            }
            rs = stm.executeQuery("select * from hero where hero_id = 2");
            while (rs.next()) {
                jTextField9.setText(rs.getInt("hero_lv")+"");
                jTextField11.setText(rs.getInt("hero_hp")+"");
                jTextField8.setText(rs.getInt("hero_atk")+"");
                jTextField12.setText(rs.getInt("hero_armor")+"");
                jTextField7.setText(rs.getInt("hero_item")+"");
                jTextField10.setText(rs.getInt("hero_exp")+"");
            }
            rs = stm.executeQuery("select * from hero where hero_id = 3");
            while (rs.next()) {
                jTextField15.setText(rs.getInt("hero_lv")+"");
                jTextField17.setText(rs.getInt("hero_hp")+"");
                jTextField14.setText(rs.getInt("hero_atk")+"");
                jTextField18.setText(rs.getInt("hero_armor")+"");
                jTextField13.setText(rs.getInt("hero_item")+"");
                jTextField16.setText(rs.getInt("hero_exp")+"");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Play.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(90, 40, 70, 30);

        jButton1.setText("SaveGame1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(165, 140, 120, 23);

        jTextField2.setEnabled(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(220, 40, 70, 30);

        jLabel1.setText("LV");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 44, 30, 20);

        jLabel2.setText("NO.1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 14, 50, 20);

        jLabel3.setText("HP");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 44, 50, 20);

        jLabel4.setText("ATK");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 50, 40, 20);

        jTextField3.setEnabled(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(360, 40, 70, 30);

        jLabel5.setText("EXP");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 90, 40, 20);

        jTextField4.setEnabled(false);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(360, 90, 70, 30);

        jLabel6.setText("ARMOR");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 90, 50, 20);

        jTextField5.setEnabled(false);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(90, 90, 70, 30);

        jLabel7.setText("ITEM");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(170, 90, 50, 20);

        jTextField6.setEnabled(false);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(220, 90, 70, 30);

        jTextField7.setEnabled(false);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(220, 240, 70, 30);

        jLabel8.setText("LV");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(31, 194, 40, 20);

        jLabel9.setText("NO.2");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 164, 50, 20);

        jLabel10.setText("HP");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(170, 194, 50, 20);

        jLabel11.setText("ATK");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(320, 194, 40, 20);

        jTextField8.setEnabled(false);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(360, 190, 70, 30);

        jTextField9.setEnabled(false);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(90, 190, 70, 30);

        jLabel12.setText("EXP");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(320, 240, 40, 20);

        jButton2.setText("SaveGame2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(165, 290, 120, 23);

        jTextField10.setEnabled(false);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(360, 240, 70, 30);

        jTextField11.setEnabled(false);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(220, 190, 70, 30);

        jLabel13.setText("ARMOR");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(27, 240, 50, 20);

        jTextField12.setEnabled(false);
        getContentPane().add(jTextField12);
        jTextField12.setBounds(90, 240, 70, 30);

        jLabel14.setText("ITEM");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(170, 240, 50, 20);

        jTextField13.setEnabled(false);
        getContentPane().add(jTextField13);
        jTextField13.setBounds(220, 410, 70, 30);

        jLabel15.setText("LV");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(31, 364, 50, 20);

        jLabel16.setText("NO.3");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(20, 334, 40, 20);

        jLabel17.setText("HP");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(170, 364, 40, 20);

        jLabel18.setText("ATK");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(320, 364, 40, 20);

        jTextField14.setEnabled(false);
        getContentPane().add(jTextField14);
        jTextField14.setBounds(360, 360, 70, 30);

        jTextField15.setEnabled(false);
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField15);
        jTextField15.setBounds(90, 360, 70, 30);

        jLabel19.setText("EXP");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(320, 410, 40, 20);

        jButton3.setText("SaveGame3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(165, 460, 120, 23);

        jTextField16.setEnabled(false);
        getContentPane().add(jTextField16);
        jTextField16.setBounds(360, 410, 70, 30);

        jTextField17.setEnabled(false);
        getContentPane().add(jTextField17);
        jTextField17.setBounds(220, 360, 70, 30);

        jLabel20.setText("ARMOR");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(27, 410, 50, 20);

        jTextField18.setEnabled(false);
        getContentPane().add(jTextField18);
        jTextField18.setBounds(90, 410, 70, 30);

        jLabel21.setText("ITEM");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(170, 410, 50, 20);

        setSize(new java.awt.Dimension(516, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Play p = new Play();
        try {
            Connection con = p.getConnection();
            PreparedStatement pm = con.prepareStatement("update hero set hero_lv = ? , hero_hp = ? , hero_armor = ? , hero_exp = ? , hero_atk = ? , hero_status = ? , hero_item = ? , hero_x2 = ? , hero_y2 = ? , item_1 = ? , item_2 = ? , item_3 = ? , item_4 = ? , item_5 = ? , miniboss = ? , boss = ? where hero_id = ?");
            pm.setInt(1, GuiBattle.hero[0]);
            pm.setInt(2, GuiBattle.hero[1]);
            pm.setInt(3, GuiBattle.hero[2]);
            pm.setInt(4, GuiBattle.hero[3]);
            pm.setInt(5, GuiBattle.hero[4]);
            pm.setInt(6, GuiBattle.hero[5]);
            pm.setInt(7, GuiBattle.hero[6]);
            pm.setInt(8, GuiBattle.hero[7]);
            pm.setInt(9, GuiBattle.hero[8]);
            pm.setBoolean(10,GuiGame.item[0]);
            pm.setBoolean(11,GuiGame.item[1]);
            pm.setBoolean(12,GuiGame.item[2]);
            pm.setBoolean(13,GuiGame.item[3]);
            pm.setBoolean(14,GuiGame.item[4]);
            pm.setBoolean(15,GuiGame.boss[0]);
            pm.setBoolean(16,GuiGame.boss[1]);
            pm.setInt(17, 1);
            pm.executeUpdate();
            con.close();
            GuiGame bg = new GuiGame();
            bg.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Play.class.getName()).log(Level.SEVERE, null, ex);
        }             
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Play p = new Play();
        try {
            Connection con = p.getConnection();
            PreparedStatement pm = con.prepareStatement("update hero set hero_lv = ? , hero_hp = ? , hero_armor = ? , hero_exp = ? , hero_atk = ? , hero_status = ? , hero_item = ? , hero_x2 = ? , hero_y2 = ? , item_1 = ? , item_2 = ? , item_3 = ? , item_4 = ? , item_5 = ? , miniboss = ? , boss = ? where hero_id = ?");
            pm.setInt(1, GuiBattle.hero[0]);
            pm.setInt(2, GuiBattle.hero[1]);
            pm.setInt(3, GuiBattle.hero[2]);
            pm.setInt(4, GuiBattle.hero[3]);
            pm.setInt(5, GuiBattle.hero[4]);
            pm.setInt(6, GuiBattle.hero[5]);
            pm.setInt(7, GuiBattle.hero[6]);
            pm.setInt(8, GuiBattle.hero[7]);
            pm.setInt(9, GuiBattle.hero[8]);
            pm.setBoolean(10,GuiGame.item[0]);
            pm.setBoolean(11,GuiGame.item[1]);
            pm.setBoolean(12,GuiGame.item[2]);
            pm.setBoolean(13,GuiGame.item[3]);
            pm.setBoolean(14,GuiGame.item[4]);
            pm.setBoolean(15,GuiGame.boss[0]);
            pm.setBoolean(16,GuiGame.boss[1]);
            pm.setInt(17, 2);
            pm.executeUpdate();
            con.close();
            GuiGame bg = new GuiGame();
            bg.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Play.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Play p = new Play();
        try {
            Connection con = p.getConnection();
            PreparedStatement pm = con.prepareStatement("update hero set hero_lv = ? , hero_hp = ? , hero_armor = ? , hero_exp = ? , hero_atk = ? , hero_status = ? , hero_item = ? , hero_x2 = ? , hero_y2 = ? , item_1 = ? , item_2 = ? , item_3 = ? , item_4 = ? , item_5 = ? , miniboss = ? , boss = ? where hero_id = ?");
            pm.setInt(1, GuiBattle.hero[0]);
            pm.setInt(2, GuiBattle.hero[1]);
            pm.setInt(3, GuiBattle.hero[2]);
            pm.setInt(4, GuiBattle.hero[3]);
            pm.setInt(5, GuiBattle.hero[4]);
            pm.setInt(6, GuiBattle.hero[5]);
            pm.setInt(7, GuiBattle.hero[6]);
            pm.setInt(8, GuiBattle.hero[7]);
            pm.setInt(9, GuiBattle.hero[8]);
            pm.setBoolean(10,GuiGame.item[0]);
            pm.setBoolean(11,GuiGame.item[1]);
            pm.setBoolean(12,GuiGame.item[2]);
            pm.setBoolean(13,GuiGame.item[3]);
            pm.setBoolean(14,GuiGame.item[4]);
            pm.setBoolean(15,GuiGame.boss[0]);
            pm.setBoolean(16,GuiGame.boss[1]);
            pm.setInt(17, 3);
            pm.executeUpdate();
            con.close();
            GuiGame bg = new GuiGame();
            bg.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Play.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiSaveGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiSaveGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiSaveGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiSaveGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiSaveGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
