/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author KMT
 */
public class GuiStart extends javax.swing.JFrame {

    /**
     * Creates new form GuiStart
     */
    public GuiStart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageJava2DGame/NewGame.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 20, 110, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageJava2DGame/LoadGame.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 80, 110, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageJava2DGame/Exit.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(20, 140, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageJava2DGame/bgStart.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);

        setSize(new java.awt.Dimension(516, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GuiBattle.hero[0] = 1;
        GuiBattle.hero[1] = 100;
        GuiBattle.hero[2] = 5;
        GuiBattle.hero[3] = 0;
        GuiBattle.hero[4] = 30;
        GuiBattle.hero[5] = 0;
        GuiBattle.hero[6] = 5;
        GuiBattle.hero[7] = 40;
        GuiBattle.hero[8] = 40;
        GuiGame.item[0]=true;
        GuiGame.item[1]=true;
        GuiGame.item[2]=true;
        GuiGame.item[3]=true;
        GuiGame.item[4]=true;
        GuiGame.boss[0]=true;
        GuiGame.boss[1]=true;
        Play p =new Play();
        try {
            Connection con = p.getConnection();
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("select * from monster");
            int i = 0, j = 0;
            while (rs.next()) {
                GuiBattle.mon[i][j] = rs.getInt("mon_hp");
                GuiBattle.mon[i][j + 1] = rs.getInt("mon_atk");
                GuiBattle.mon[i][j + 2] = rs.getInt("mon_exp");
                GuiBattle.mon[i][j + 3] = rs.getInt("mon_lv");
                i++;
            }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Play.class.getName()).log(Level.SEVERE, null, ex);
        }
        GuiGame gui=new GuiGame();
        gui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Play p =new Play();
        try {
            Connection con = p.getConnection();
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("select * from monster");
            int i = 0, j = 0;
            while (rs.next()) {
                GuiBattle.mon[i][j] = rs.getInt("mon_hp");
                GuiBattle.mon[i][j + 1] = rs.getInt("mon_atk");
                GuiBattle.mon[i][j + 2] = rs.getInt("mon_exp");
                GuiBattle.mon[i][j + 3] = rs.getInt("mon_lv");
                i++;
            }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Play.class.getName()).log(Level.SEVERE, null, ex);
        }
        GuiLoadSave gui = new GuiLoadSave();
        gui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiStart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
